### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by dimitry-ishenko** [rparkins999/sqliteman#5]
This is a great program but needs to be ported to Qt5

**Comment by albel727** [comment]
There's an older fork with Qt5 support.

https://github.com/Chemrat/sqliteman

Unfortunately, it stopped compiling with Qt 5.7.

**Comment by rparkins999** [comment]
The problem for me is that my platform (kubuntu 14) has no prebuilt Qt5 libraries avallable, and it is a lot of work with no benefit for me to build a QT5 library from the sources and then update sqliteman to work with it. Anyone who wants to fork and build a Qt5 version is very welcome to do so. Alternatively you can wait until I get Qt5. I don't know when that will be, because at present my upgrade path is broken.

A fork from the original pvanek/sqliteman is likely to be very out of date with respect to this version: it won't have all my bug fixes and updates.

**Comment by platipusica** [comment]
Hello there!

I concur with the above request. Spent half a day yesterday trying to compile with my limited QT knowledge. On and old Linuxx Mint this was a breeze with QT4.

On that note, if ever released, can we have the Populate option for at least one million records max? Having 1000 records is nothing this days :)

Cheers

**Comment by rparkins999** [comment]
"Spent half a day yesterday trying to compile with my limited QT knowledge."

That's exactly the problem. My QT knowledge is limited too. I have also put in a lot of code to work around Qt4 bugs, and some problems which aren't actually bugs but prevent me from making the UI work the way that i want it to. Some of those bugs and problems may be fixed in Qt5, but I have no way of knowing which, and Qt5 will have its own new lot of bugs and problems.

It would take a lot of work to make a Qt5 version which works as well as the QT4 one does now, and to what end? Nobody is paying me for this: I work on sqliteman because I use it a lot myself. If your Linux distro doesn't have Qt4, you can almost certainly install it.

**Comment by rparkins999** [comment]
"can we have the Populate option for at least one million records max"

It would be _very_ slow. Populate is implemented, if I recall correctly, by creating records one at a time. Qt's layer over sqlite does this quite slowly, and the more records there are already in the database, the slower it gets. Why would you want to create such a large number of random records anyway? If you really want to create a lot of records, it would be much faster to do it with an SQL statement, even if you include the time to read the sqlite documentation.

Of course the whole point of sqliteman is to be able to do simple things without writing SQL code, but creating a million records isn't a simple thing, and I certainly have no use for it.

I'll look into increasing the limit, but it has a low priority for me. If you can build the Qt4 version, you can try increasing the limit yourself.
